version: "3.8"

services:
  redis: # container name
    image: redis:6.2.6-alpine
    container_name: ticket_coupon_redis
    ports: # 바인딩할 포트:내부 포트
      - 6380:6380
    command: redis-server --port 6380
    restart: always
