version: "3.8"
services:
  mysql:
    container_name: mariadb_local
    image: mariadb:10.5
    volumes:
      - ./db:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - TZ=Asia/Seoul
    restart: always
